### ISSUE TITLE
Potentially copyrighted code from CatWar

### ISSUE THREAD

**Issue by LeviPesin** [17Nei17/gameDootoRats#1]
извините а можно вопрос зачем у вас в репе варовский ко и варовская охота
и наверное они закопирайчены и их нельзя копировать... (в гитхабе насколько помню по умолчанию отсутствие лицензии = запрещающая лицензия, в репозитории ко лицензии нет)

**Comment by 17Nei17** [comment]
Привет. Тут точно нет охоты варовской. 
Однако ты прав про вароский КО.
Его наличие тут связано с беспорядком.
У меня были попытки попробовать переписать КО на реакт, чтобы выиграть в оптимизации и поправить возможно дизайн, поэтому тут присутствует его код.
А потом появилась маленькая внезапная идея про ритм-игру с кирпекотом, изначально было ноль планов на ее публикацию и доведение до конца, а все происходило на уровне "проверю как это будет работает", из-за чего на данный момент у меня одна репа на два проекта. (я понимаю что это звучит бредово, но так вышло.) 
И в ближайшее время я уберу лишнее, этому коду КО место в форкнутом репозитории КО.
Форк - насколько я знаю, ничего не нарушает.

**Comment by LeviPesin** [comment]
> Тут точно нет охоты варовской.

https://github.com/17Nei17/gameDootoRats/blob/master/src/test.js
что она у вас делает в тестах -- никаких идей

**Comment by 17Nei17** [comment]
Удалила, приношу свои извинения.

**Comment by 17Nei17** [comment]
Благо это не исходник, а вытянутый с браузера в уже собранном виде вебпаком (предположительно) код.

Есть ли еще замечания?

**Comment by LeviPesin** [comment]
> Удалила, приношу свои извинения.

ну я не админ вара и даже уже очень долго не варовец, не надо передо мной извиняться)
